# Generated by Django 5.1.2 on 2025-03-08 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_incharge_phone', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_phone', models.CharField(max_length=11)),
                ('slug', models.SlugField(max_length=80)),
                ('branch_incharge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch_under_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officeRelated.location')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_phone', models.CharField(max_length=11)),
                ('sender_address', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_phone', models.CharField(max_length=11)),
                ('receiver_address', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('parcel_type', models.CharField(max_length=100)),
                ('parcel_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isHomeDelivery', models.BooleanField(default=False)),
                ('parcel_bill', models.IntegerField()),
                ('parcel_status', models.CharField(choices=[('On the way', 'On the way'), ('Arrived', 'Arrived'), ('Received', 'Received'), ('Delivered', 'Delivered')], default='On the way', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isSoftDelete', models.BooleanField(default=False)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('receiving_branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='officeRelated.branch')),
                ('sending_branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sending_branch', to='officeRelated.branch')),
            ],
        ),
    ]
